name: Trigger Target Workflow 4

on: [workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "Trigger Project Test"
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.PAT }}
          repo: test-target-repository
          owner: kifir23917
          workflow: target_workflow.yml
          ref: main
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.PAT }}
          repo: kifir23917
          owner: target_workflow.yml
          ref: main
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional