on: [workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "Trigger Project Test"
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_AUTHOR: ${{ github.author }}
          PAYLOAD_REVISION: "3"
        with:
          repository: kifir23917/test-target-repository
          event: trigger-workflow
          github_pat: ${{ secrets.PAT }}